name: Fuzzing

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  security-events: write   # нужно, чтобы загружать артефакты

jobs:
  ffuf:
    runs-on: ubuntu-latest

    services:
      juice:
        image: bkimminich/juice-shop            # последний стабильный образ
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -fs http://localhost:3000 || exit 1"
          --health-interval=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget jq
          go install github.com/ffuf/ffuf/v2@latest

      - name: Download SQL‑i payloads
        run: |
          wget -qO payloads.txt \
            https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/master/SQL%20Injection/Intruder/SQL-Injection

      - name: Run fuzz‑login.sh
        run: |
          chmod +x scripts/fuzz-login.sh
          ./scripts/fuzz-login.sh payloads.txt artifacts

      - name: Save Juice Shop logs
        run: |
          docker logs ${{ job.services.juice.id }} > artifacts/juice-logs.log

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: artifacts

          
