name: Fuzzing Juice Shop login

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  security-events: write   # для артефактов

jobs:
  fuzz:
    runs-on: ubuntu-latest

    services:
      juice:
        image: bkimminich/juice-shop:latest
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
            set -e
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update -qq
            sudo apt-get install -y --no-install-recommends \
                 wget jq curl git golang-go ca-certificates
            sudo update-ca-certificates      # если нужен
            echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
            go install github.com/ffuf/ffuf/v2@latest


      # ждём, пока приложение действительно поднимется
      - name: Wait for Juice Shop
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:3000/ > /dev/null; then
              echo "Juice Shop is ready"; exit 0
            fi
            sleep 2
          done
          echo "Juice Shop did not start in time" >&2
          docker ps -a
          docker logs $(docker ps -aqf "name=juice") || true
          exit 1

      - name: Download SQL‑i payloads
        run: |
          wget -qO payloads.txt \
            https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/master/SQL%20Injection/Intruder/SQL-Injection

      - name: Run fuzz‑login.sh
        run: |
          chmod +x scripts/fuzz-login.sh
          ./scripts/fuzz-login.sh payloads.txt artifacts http://localhost:3000

      - name: Save Juice Shop logs
        run: docker logs $(docker ps -aqf "name=juice") > artifacts/juice-logs.log

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: artifacts
