name: Fuzzing Juice Shop login

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  security-events: write   # для артефактов

jobs:
  fuzz:
    runs-on: ubuntu-latest

    # Запустим сам job в лёгком контейнере Ubuntu – тогда
    # и job‑контейнер, и service‑контейнер окажутся
    # в одной Docker‑сети GitHub Actions.
    container: ubuntu:22.04

    services:
      juice:
        image: bkimminich/juice-shop:latest
        # убираем healthcheck – будем ждать вручную
        options: >-
          --name juice

    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
          apt-get update -qq
          apt-get install -y wget jq curl
          go install github.com/ffuf/ffuf/v2@latest

      # ждём, пока приложение действительно поднимется
      - name: Wait for Juice Shop
        run: |
          for i in {1..60}; do
            if curl -sSf http://juice:3000/ > /dev/null; then
              echo "Juice Shop is ready"; exit 0
            fi
            sleep 2
          done
          echo "Juice Shop did not start in time" >&2
          docker logs juice || true
          exit 1

      - name: Download SQL‑i payloads
        run: |
          wget -qO payloads.txt \
            https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/master/SQL%20Injection/Intruder/SQL-Injection

      - name: Run fuzz‑login.sh
        run: |
          chmod +x scripts/fuzz-login.sh
          ./scripts/fuzz-login.sh payloads.txt artifacts http://juice:3000

      - name: Save Juice Shop logs
        run: docker logs juice > artifacts/juice-logs.log

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: artifacts
